# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
