# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20170516_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Film'),
        ),
    ]
