# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20170516_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
